# Generated by Django 5.0.2 on 2024-04-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_author_book_is_bestselling_alter_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_id', models.IntegerField()),
                ('isbookissued', models.BooleanField(default=True)),
            ],
        ),
    ]
