# Generated by Django 5.0.2 on 2024-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_address_author_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adrress_Entries'},
        ),
        migrations.AddField(
            model_name='book',
            name='countries_published',
            field=models.ManyToManyField(to='store.country'),
        ),
    ]
